[package]
name = "puppeteer-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
proc-macro2 = "1.0.32"

[dependencies.syn]
version = "1.0.81"
features = ["extra-traits"]